name: Run Job on PR Merge

on:
  push:
    branches:
      - main # マージ先のブランチを指定

jobs:
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check allowed user with contains
        if: contains(secrets.ALLOWEDUSER, github.actor)
        run: echo "Hello"